RunNamePlaceholder: '{runname}'
RunPointsNamePlaceholder: '{runpointsname}'
RunPointsAmountPlaceholder: '{runpointsamount}'


ItemPricePlaceholder: '{price}'
ShopNamePlaceholder: '{shopname}'

MembersJoinedPlaceholder: '{membersjoined}'
ActiveMembersNamesPlaceholder: '{playersinlobby}'
LobbyIDPlaceholder: '{lobbyid}'
LeftOverMinutesPlaceholder: '{leftovertime}'

AmountOfPlayers: 5

DemonRun:
  name: '§eDémon run'
  ThisRunPointsName: 'Démon Point'
  ThisRunPointsAmount: 2
  ThisRunNPCstartName: 'Demon Guard'
  PlayGUIopenPermission: 'demonrun.canplay'
  NumberOfAvailableRuns: 3
  WoolNameWhenCanJoin: '#{lobbyid} §eJoin this run'
  WoolNameWhenCanNotJoin: '#{lobbyid} §cThis run ends in {leftovertime} mins'
  WoolLore:
    - 'There are {membersjoined} players in this lobby.'
    - '§bPlayers:'
    - '{playersinlobby}'
    - 'You get {runpointsamount} {runpointsname}s if you finish this run'
  PlayTimeInMinutes: 20
  BossBarTitle: '{runname} - You have {leftovertime} mins left'
  RunProcessInformation:
    1:
      level_0:
        WorldNameCheckPoint: 'DemonWorld1'
        CheckPointLocation: '235 64 -129'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Auror'
        KeyItemDisplayName: 'StoneKey'
        WorldNameTeleport: 'DemonWorld1'
        TeleportToLocation: '266 50 -100'
        FinalLevel: false
      level_1:
        WorldNameCheckPoint: 'DemonWorld1'
        CheckPointLocation: '266 50 -100'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Euror'
        KeyItemDisplayName: 'GoldKey'
        WorldNameTeleport: 'DemonWorld1'
        TeleportToLocation: '290 55 -70'
        FinalLevel: false
      level_3:
        WorldNameCheckPoint: 'DemonWorld1'
        CheckPointLocation: '290 55 -70'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Geuror'
        KeyItemDisplayName: 'DiamondKey'
        WorldNameTeleport: 'DemonWorld1'
        TeleportToLocation: '310 55 -50'
        FinalLevel: false
      level_4:
        WorldNameCheckPoint: 'DemonWorld1'
        CheckPointLocation: '310 55 -50'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Feuror'
        KeyItemDisplayName: 'EmeraldKey'
        WorldNameTeleport: 'StartWorld'
        TeleportToLocation: '200 6 200'
        FinalLevel: true
    2:
      level_0:
        WorldNameCheckPoint: 'DemonWorld2'
        CheckPointLocation: '235 64 -129'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Auror'
        KeyItemDisplayName: 'StoneKey'
        WorldNameTeleport: 'DemonWorld2'
        TeleportToLocation: '266 50 -100'
        FinalLevel: false
      level_1:
        WorldNameCheckPoint: 'DemonWorld2'
        CheckPointLocation: '266 50 -100'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Euror'
        KeyItemDisplayName: 'GoldKey'
        WorldNameTeleport: 'DemonWorld2'
        TeleportToLocation: '290 55 -70'
        FinalLevel: false
      level_3:
        WorldNameCheckPoint: 'DemonWorld2'
        CheckPointLocation: '290 55 -70'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Geuror'
        KeyItemDisplayName: 'DiamondKey'
        WorldNameTeleport: 'DemonWorld2'
        TeleportToLocation: '310 55 -50'
        FinalLevel: false
      level_4:
        WorldNameCheckPoint: 'DemonWorld2'
        CheckPointLocation: '310 55 -50'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Feuror'
        KeyItemDisplayName: 'EmeraldKey'
        WorldNameTeleport: 'StartWorld'
        TeleportToLocation: '200 6 200'
        FinalLevel: true
    3:
      level_0:
        WorldNameCheckPoint: 'DemonWorld3'
        CheckPointLocation: '235 64 -129'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Auror'
        KeyItemDisplayName: 'StoneKey'
        WorldNameTeleport: 'DemonWorld3'
        TeleportToLocation: '266 50 -100'
        FinalLevel: false
      level_1:
        WorldNameCheckPoint: 'DemonWorld3'
        CheckPointLocation: '266 50 -100'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Euror'
        KeyItemDisplayName: 'GoldKey'
        WorldNameTeleport: 'DemonWorld3'
        TeleportToLocation: '290 55 -70'
        FinalLevel: false
      level_3:
        WorldNameCheckPoint: 'DemonWorld3'
        CheckPointLocation: '290 55 -70'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Geuror'
        KeyItemDisplayName: 'DiamondKey'
        WorldNameTeleport: 'DemonWorld3'
        TeleportToLocation: '310 55 -50'
        FinalLevel: false
      level_4:
        WorldNameCheckPoint: 'DemonWorld3'
        CheckPointLocation: '310 55 -50'
        ServerCommand: '/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z>'
        NPCname: 'Feuror'
        KeyItemDisplayName: 'EmeraldKey'
        WorldNameTeleport: 'StartWorld'
        TeleportToLocation: '200 6 200'
        FinalLevel: true

LobbyFullMsg: 'This lobby is full. Please wait for it to finish.'
RunStartMsg: 'The lobby is full! The run starts in 10 seconds.'
PassedLevelMsg: 'You handed the key over. Your team is being teleported to the next level.'
RunFinishMsg: 'You successfully defeated the final boss and completed the run. You earned {runpointsamount} {runpointsname}s.'
CanNotLeaveMsg: 'Sorry, but you cannot leave your group while you are in a run. Please, finish the run first.'
BackInGameMsg: 'You came back and the run is still on, you got teleported to the last checkpoint.'
CouldNotFinishInTimeMsg: "You didn't finish the game in time. You have been teleported out."
AllPlayersDeadMsg: 'All players in the run have died. The run is over.'
MobrunShopAddCommandSuccessMsg: 'You successfully copied the data of the item in your hand to {shopname} §rwith the price set to {price}§r.'
LobbyJoinMsg: 'You joined the lobby!'
LobbyLeaveMsg: 'You left the lobby.'
TimeoutMsg: 'You timed out of the lobby!'
AlreadyInLobbyMsg: "You're already in a lobby!"

CanNotOpenShopGUImsg: "Sorry, but you can't shop here yet."
ShopNotEnoughPointsMsg: "You don't have enough points to buy this item."
ShopBoughtSuccessfullyMsg: 'You successfully bought this item.'
AfterShutDown1Msg: 'The server has been down, therefore the run is over. You lost your progress.'
AfterShutDown2Msg: "If the shutdown wasn't planned and broadcasted in time, contact the admins. Otherwise, we can't do anything. Sorry."

CanNotOpenRunGUImsg: "Sorry, but you aren't allowed to play this run yet."
DisplayRunPointsMsg: 'You currently have the following amount of runpoints:'

MobrunShopCreateCommandSuccessMsg: "You successfully created a shop in the config. Please go to the config file and edit it. Please note that this shop won't start working until the server is restarted."
MobrunShopCreateCommandFailureMsg: 'A shop with this name already exists.'
MobrunShopAddCommandFailureMsg: 'You cannot add any items to that shop, because the config is invalid.'